//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication34.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public long ProductID { get; set; }
        public Nullable<long> OwnerID { get; set; }
        public Nullable<long> UserID { get; set; }
        public string Title { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Price { get; set; }
        public string Picture1 { get; set; }
        public string Picture2 { get; set; }
        public string Picture3 { get; set; }
        public int State { get; set; }
        public Nullable<System.DateTime> DateAddedToCart { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
